In [2]:
import numpy as np

In [7]:
#reshape
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
#split
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [15]:
np.split(a,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [17]:
#resize
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.resize(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.resize(a,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [23]:
#append
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#insert

In [33]:
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.insert(a,1,[10],axis=0)

array([[ 1,  2],
       [10, 10],
       [ 3,  4],
       [ 5,  6]])

In [37]:
np.insert(a,1,[10],axis=1)

array([[ 1, 10,  2],
       [ 3, 10,  4],
       [ 5, 10,  6]])

In [39]:
#delete
a = np.arange(12).reshape(3,4) 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.delete(a,1,axis=0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [43]:
np.delete(a,1,axis=1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [45]:
#unique
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [46]:
np.unique(a)

array([2, 5, 6, 7, 8, 9])