In [79]:
import numpy as np

In [ ]:
#The most important object defined in NumPy is an N-dimensional array type called ndarray. 
#It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.
#The basic ndarray object is created using an array function in NumPy..

In [114]:
a = np.array([1,2,3])

In [ ]:
#why do use ndarray or array object...it take less memory and high speed...
#and also allow to do mathematical and logical operations on array

In [115]:
a

array([1, 2, 3])

In [116]:
type(a)

numpy.ndarray

In [117]:
a[1]

2

In [125]:
# more than one dimensions 
b= np.array([[1,2],[3,4]])

In [126]:
b

array([[1, 2],
       [3, 4]])

In [127]:
b[0]

array([1, 2])

In [128]:
b[0][1]

2

In [130]:
#This array attribute returns a tuple consisting of array dimensions
b.shape

(2, 2)

In [136]:
#This array attribute returns the number of array dimensions.
b.ndim

2

In [138]:
#This array attribute returns the length of each element of array in bytes
b.itemsize

4

In [149]:
#It creates an uninitialized array of specified shape and dtype
x = np.empty([2,3],dtype=int)
x

array([[1739140304,        497,          0],
       [         0,     131074,          0]])

In [152]:
#Returns a new array of specified size, filled with zeros.
x= np.zeros([2,3],dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0]])

In [154]:
#Returns a new array of specified size and type, filled with ones.
x= np.ones([2,3],dtype=int)
x

array([[1, 1, 1],
       [1, 1, 1]])