In [2]:
import numpy as np

In [3]:
#numpy.asarray

In [5]:
x=[1,2,3]
a=np.asarray(x)
a

array([1, 2, 3])

In [7]:
x=(1,2,3)
a=np.asarray(x)
a

array([1, 2, 3])

In [9]:
x=[(1,2,3),(4,5)]
a=np.asarray(x)
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [11]:
#numpy.fromiter
rng=range(6)

In [20]:
it =iter(rng)
it

In [21]:
a = np.fromiter(it,dtype=int)
a

array([0, 1, 2, 3, 4, 5])

In [24]:
#numpy.arange
x= np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
x= np.arange(2,8)
x

array([2, 3, 4, 5, 6, 7])

In [28]:
x= np.arange(2,8,2)
x

array([2, 4, 6])

In [30]:
#numpy.linspace
x = np.linspace(10,20,5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [35]:
x = np.linspace(10,21,5,retstep=True)
x

(array([10.  , 12.75, 15.5 , 18.25, 21.  ]), 2.75)

In [37]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [38]:
for a in np.nditer(x):
    print(a)

0
1
2
3
4
